# Generated by Django 4.1.3 on 2022-12-06 08:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Battery')),
                ('min_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimal capacity')),
                ('configuration', models.TextField(max_length=15, verbose_name='Configuration')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Length')),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Width')),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Height')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Charger')),
                ('input_voltage', models.TextField(max_length=20, verbose_name='Input Voltage')),
                ('output_voltage', models.TextField(max_length=20, verbose_name='Output Voltage')),
                ('power_output', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Power')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Remote control')),
                ('max_pull', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Pull per Axis')),
                ('recommended_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Recommended weight per Axis')),
                ('min_work_temp', models.IntegerField(verbose_name='Minimal working temperature')),
                ('max_work_temp', models.IntegerField(verbose_name='Maximum working temperature')),
                ('combo_weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Combo weight')),
                ('waterproof', models.TextField(verbose_name='Waterproof')),
                ('rated_power', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rated power')),
                ('starter_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Starter length')),
                ('starter_width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Starter width')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Nozzles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nozzles')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Propeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Propeller')),
                ('diameter_step', models.TextField(verbose_name='Diameter*Step')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Pump')),
                ('min_work_voltage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimal working voltage')),
                ('max_work_voltage', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum working voltage')),
                ('consumption', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumption')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='RemoteControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Remote control')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Tank')),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Capacity')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Unmanned aerial vehicle')),
                ('description', models.TextField(max_length=255, verbose_name='Description')),
                ('deployed_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deployed length')),
                ('deployed_width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deployed width')),
                ('deployed_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Deployed height')),
                ('rolled_up_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rolled up length')),
                ('rolled_up_width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rolled up width')),
                ('rolled_up_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rolled up height')),
                ('weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight')),
                ('max_weight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Weight')),
                ('speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Speed')),
                ('max_speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max speed')),
                ('flight_time_full', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Flight time with full tank')),
                ('flight_time_empty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Flight time with empty tank')),
                ('area_per_flight', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Area per 1 flight')),
                ('area_per_hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Area per 1 hour')),
                ('tank', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tank')),
                ('drop_size', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Drop size')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('status', models.TextField(verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneSelling.battery')),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneSelling.charger')),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneSelling.engine')),
                ('nozzles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneSelling.nozzles')),
                ('propeller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneSelling.propeller')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneSelling.pump')),
                ('remote_control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneSelling.remotecontrol')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneSelling.tank')),
                ('uav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneSelling.uav')),
            ],
        ),
    ]
