# Generated by Django 4.1.3 on 2022-12-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droneSelling', '0004_electroniccard'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.TextField(default='Tech Service', verbose_name='Request type'),
        ),
    ]
