# Generated by Django 4.1.3 on 2024-02-06 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('droneSelling', '0011_completedtechcard_completedtechoperation_drone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='drone_type_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='droneSelling.dronetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='drone_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='droneSelling.drone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 13, 32, 21, 398627), verbose_name='request date'),
        ),
    ]
