# Generated by Django 4.1.3 on 2024-02-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droneSelling', '0018_alter_request_request_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleRequest',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='drone_type_id',
            new_name='drone_id',
        ),
        migrations.RenameField(
            model_name='techcard',
            old_name='dronetype_id',
            new_name='drone_type_id',
        ),
        migrations.AddField(
            model_name='request',
            name='response',
            field=models.TextField(default=None, verbose_name='response'),
        ),
    ]
