# Generated by Django 4.1.3 on 2024-02-10 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('droneSelling', '0019_delete_simplerequest_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='name',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='dronetype',
            old_name='model',
            new_name='type',
        ),
    ]
