# Generated by Django 4.1.3 on 2024-02-20 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('droneSelling', '0020_rename_name_drone_model_rename_model_dronetype_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='ServiceRules',
        ),
        migrations.RenameField(
            model_name='servicerules',
            old_name='drone_id',
            new_name='drone_type_id',
        ),
        migrations.AddField(
            model_name='drone',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
