# Generated by Django 4.1.3 on 2024-02-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('droneSelling', '0022_alter_request_repair_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.TextField(default=None, null=True, verbose_name='response'),
        ),
    ]
