# Generated by Django 4.1.3 on 2022-12-07 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uavSelling', '0005_request_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='article',
            field=models.TextField(default='№', verbose_name='Article'),
        ),
        migrations.AddField(
            model_name='request',
            name='uav',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uavSelling.uav'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uav',
            name='serial_id',
            field=models.TextField(default='0', verbose_name='Serial Id'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.TextField(default='None', verbose_name='Request type'),
        ),
    ]
