# Generated by Django 4.1.3 on 2022-12-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uavSelling', '0007_request_time_create_request_time_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='request',
            name='time_update',
        ),
    ]
