# Generated by Django 4.1.3 on 2024-02-06 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uavSelling', '0012_drone_drone_type_id_flight_drone_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtechcard',
            name='comp_tech_oper_id',
        ),
        migrations.RemoveField(
            model_name='dronetype',
            name='techcard_id',
        ),
        migrations.RemoveField(
            model_name='techcard',
            name='instruction_order',
        ),
        migrations.RemoveField(
            model_name='techcard',
            name='tech_op_id',
        ),
        migrations.AddField(
            model_name='completedtechoperation',
            name='comp_techcard_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uavSelling.completedtechcard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='drone_type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uavSelling.dronetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techcard',
            name='description',
            field=models.CharField(default='description', max_length=20, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techcard',
            name='dronetype_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uavSelling.dronetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techoperation',
            name='description',
            field=models.CharField(default='description', max_length=20, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techoperation',
            name='instruction_order',
            field=models.IntegerField(default=1, verbose_name='instruction order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techoperation',
            name='techcard_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='uavSelling.techcard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 19, 52, 15, 143349), verbose_name='request date'),
        ),
    ]
