# Generated by Django 4.1.3 on 2024-02-06 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uavSelling', '0013_remove_completedtechcard_comp_tech_oper_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techoperation',
            name='html_content',
            field=models.URLField(default='html', verbose_name='html-content'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 19, 56, 29, 612451), verbose_name='request date'),
        ),
    ]
