# Generated by Django 4.1.3 on 2024-02-06 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uavSelling', '0016_alter_request_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 6, 20, 5, 20, 799647), verbose_name='request date'),
        ),
    ]
